name: trees
channels:
  - defaults
  - conda-forge
dependencies:
  # Base packages
  - pip
  - python=3.*
  - jupyterlab
  - rope
  # Additional packages
  - pandas
  - flask
  - sqlalchemy
  - psycopg2
